### ISSUE TITLE
Unsatisfiable constraints error

### ISSUE THREAD

**Issue by clayrisser** [NeoAssist/docker-keepalived#11]
I get the following issue when I try and build the docker container from the Dockerfile.

```
Step 2 : RUN echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && apk --update -t add keepalived iproute2 grep bash tcpdump sed && rm -f /var/cache/apk/* /tmp/*
 ---> Running in b588e66b2363
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  so:libcrypto.so.38 (missing):
    required by:
                 keepalived-common-1.2.23-r2[so:libcrypto.so.38]
                 keepalived-1.2.23-r2[so:libcrypto.so.38]
  so:libssl.so.39 (missing):
    required by:
                 keepalived-common-1.2.23-r2[so:libssl.so.39]
                 keepalived-1.2.23-r2[so:libssl.so.39]
  add-0:
    masked in: cache
    satisfies: world[add]
The command '/bin/sh -c echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && apk --update -t add keepalived iproute2 grep bash tcpdump sed && rm -f /var/cache/apk/* /tmp/*' returned a non-zero code: 5

```

**Comment by roynasser** [comment]
Hi @jamrizzi I will have to take a better look at this...  It is probably due to the fact we are using "relative" tags in the base image, and these evolve over time...  Its not the ideal IMO, and when going to production we should maybe try to fix version numbers...

I seem to recall that there was a particular reason for doing the apk update through the edge channel...  If I'm not mistaken we needed some options that were only working on the edge channel.  Nonetheless, your proposed change on the PR is bumping the entire image to edge, which could "fix" the problem, but can introduce other issues we arent aware of...

I'm more inclined to find a version that works for tagging and leaving it on latest/edge only for development & testing, always fixing the version when tagging a release (thus preventing bugs from "appearing" when alpine changes its tags)...

**Comment by sjiveson** [comment]
This is due to Alpine dropping support for OpenSSL rather suddenly a week or two ago. We'll need to added the main repository for the edge branch and add libressl to the apk install command. I'm happy to do this but I'm worried I'll break things now we're 'releasing' so please advise if I can do this directly or should do something else?

**Comment by roynasser** [comment]
@sjiveson I figured it was something related to openssl...  There are some openssl-related merges in the alpine docker image recently...

Anyways, you can go ahead and make PRs or Merges into the master, and once we can test it on a couple of systems we can tag that...  I fear that the change may have "broken" the package for anyone who tries to build it...  Thats why I would suggest tagging against a specific version number, what do you think?

**Comment by sjiveson** [comment]
In this case tagging against, say 3.4 wouldn't help as they simply ripped openssl out of every branch and repo. Anyway, I'll make the changes locally now quickly and post back and update here once I've tested.

**Comment by sjiveson** [comment]
OK, just adding the edge/main repo did the trick and the image built just fine using LibreSSL. Merged directly into master.

**Comment by sjiveson** [comment]
Gotta drive home now (90mins+) but tagging alpine versions would probably be wise I'd say. We can create a new release for new Alpine releases fairly simply and provide a bit more predictability.

**Comment by sjiveson** [comment]
OK, pinned to Alpine v3.4. I'll leave it to @RVN-BR to deal with creating releases. Both issues resolved, I'll close this.
